// Generated by pnpm sync — do not edit by hand.
export const CHAIN_ID = 10143 as const;
export const DEPLOYED_BLOCK = 57923009 as const;
export const VENUE_MODE = "sim" as const;

export const ADDRESSES = {
  "Ballast": "0xCD694B5C79D12708F11FB1adF1594e8e71de650D",
  "BlitzVault": "0x27eE1688F8b07E2aa767a4B4f4b90040E3ABC55d",
  "DemoUSD": "0x959E54DcF8576856F7A9424190a9751c68739495",
  "EngineLite": "0x60eC904955CA843285B24E3F6e7e2034F8f96140",
  "Guardian": "0x75Bf4C326f054e655C7C138cD847154fEB3bAC19",
  "Hull": "0x9638da84aA4b30fB9350bb2cA33DCf0b81Ab3Bd2",
  "MockRouter": "0x68A1Ad5FB46c3Eb804F3375Cba702d806E1890B6",
  "MockWMON": "0xEf6Cc6228A39cF8433754dcBe863275AC6Dc5DB5",
  "PerplVenue": "0x59fc4C09eF7Dc0b754B74d7AEe21EeAC1c94aD6C",
  "SimVenue": "0xD8730205Ab716Bc2FcA2FfF653e1390DFC4Fe85d",
  "Tranches": "0x7Df78EA918FA4531a74b79CE0a53a6D94B72E373"
} as const;

export const REFS = {
  "explorerMainnet": "https://monadvision.com",
  "explorerTestnet": "https://testnet.monadvision.com",
  "puddleRouter": "0x430c23895c8D44883526e3E0B09327dAD8766660",
  "rpcMainnet": "https://rpc.monad.xyz",
  "rpcTestnet": "https://testnet-rpc.monad.xyz",
  "wmonMainnet": "0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A",
  "wmonTestnet": "0xFb8bf4c1CC7a94c73D209a149eA2AbEa852BC541"
} as const;

export function assertChain(chainId: number) {
  if (chainId !== CHAIN_ID) {
    throw new Error(`Wrong chain: expected ${CHAIN_ID}, got ${chainId}`);
  }
}
