// Generated by pnpm sync — do not edit by hand.
export const CHAIN_ID = 10143 as const;
export const DEPLOYED_BLOCK = 57918591 as const;
export const VENUE_MODE = "sim" as const;

export const ADDRESSES = {
  "Ballast": "0x074207acEf2f60a6B1B86a885D2fF893927109A1",
  "BlitzVault": "0xE1c3aBAd2789aC170833d9E9bd72E706284a70c5",
  "DemoUSD": "0x66B5A41466b1Ab2dE34Bf3834b26F99bA4f52e05",
  "EngineLite": "0xDE65E58df3e3da55DD3c6e107E30E1655Fb5fC85",
  "Guardian": "0x150e153D5aB4683EC576bC1F68b7839D86751208",
  "Hull": "0xC053Fc6968BAd0FB03094E002a4F4EC74a746f12",
  "MockRouter": "0x23389cA2fbf11f9D0159EF2F80A963E710c5F97C",
  "MockWMON": "0x17141F36c4401C6184143250827713b26c3E964F",
  "PerplVenue": "0xaf1C0BdEaF91273E18a80bF80afD8A5C6d497C21",
  "SimVenue": "0xAbE34e4919e7Ffd5C87D5B62d35f7E7Bb4e50FD7",
  "Tranches": "0xdb4666c3F187e73795bcF9Cfb3a6D64A875EF842"
} as const;

export const REFS = {
  "explorerMainnet": "https://monadvision.com",
  "explorerTestnet": "https://testnet.monadvision.com",
  "puddleRouter": "0x430c23895c8D44883526e3E0B09327dAD8766660",
  "rpcMainnet": "https://rpc.monad.xyz",
  "rpcTestnet": "https://testnet-rpc.monad.xyz",
  "wmonMainnet": "0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A",
  "wmonTestnet": "0xFb8bf4c1CC7a94c73D209a149eA2AbEa852BC541"
} as const;

export function assertChain(chainId: number) {
  if (chainId !== CHAIN_ID) {
    throw new Error(`Wrong chain: expected ${CHAIN_ID}, got ${chainId}`);
  }
}
