// Generated by `pnpm verify:manifest` (scripts/verify-manifest.mjs) — do not edit by hand.
//
// Per-contract source-verification state for the Transparency screen. A row
// renders the VERIFIED badge only where state is "verified"; everything else
// renders a dim, explicit label. Every contract is seeded "unknown" because
// nothing has been re-verified against the coming redeploy — hand-editing a
// state here would put the old false claim straight back on the page.
//
// Regenerate after a verification run:
//   pnpm verify:manifest --results <results.json>

export type VerificationState = "verified" | "unverified" | "unknown";

export type VerificationEntry = {
  state: VerificationState;
  /** ISO-8601 instant the state was established, or null if never checked. */
  checkedAt: string | null;
  /** The exact address this state was checked against. A redeploy moves this,
   *  and the parity test then fails rather than letting a stale badge ride. */
  address: string;
  /** Link to the verification evidence, when the run produced one. */
  url?: string;
};

export const VERIFICATION: Record<string, VerificationEntry> = {
  "AssetCustody": { state: "verified", checkedAt: "2026-10-02T14:19:53Z", address: "0x800b830A3B6C63bcAABAa9128A217a03aaD7377d", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x800b830A3B6C63bcAABAa9128A217a03aaD7377d" },
  "Ballast": { state: "verified", checkedAt: "2026-08-29T12:22:48Z", address: "0xCD694B5C79D12708F11FB1adF1594e8e71de650D", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0xCD694B5C79D12708F11FB1adF1594e8e71de650D" },
  "BallastToken": { state: "verified", checkedAt: "2026-10-02T14:20:05Z", address: "0x278E531dBc080Fa4C0314da9c1592bA6f148926d", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x278E531dBc080Fa4C0314da9c1592bA6f148926d" },
  "BlitzVault": { state: "verified", checkedAt: "2026-08-29T12:22:02Z", address: "0x27eE1688F8b07E2aa767a4B4f4b90040E3ABC55d", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x27eE1688F8b07E2aa767a4B4f4b90040E3ABC55d" },
  "ClaimEscrow": { state: "verified", checkedAt: "2026-10-02T14:19:59Z", address: "0x6B60BcdF3a2DB8762Ade4b05D590aB0aCf0FDF3d", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x6B60BcdF3a2DB8762Ade4b05D590aB0aCf0FDF3d" },
  "DemoUSD": { state: "verified", checkedAt: "2026-08-29T12:21:50Z", address: "0x959E54DcF8576856F7A9424190a9751c68739495", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x959E54DcF8576856F7A9424190a9751c68739495" },
  "EngineLite": { state: "verified", checkedAt: "2026-08-29T12:22:18Z", address: "0x60eC904955CA843285B24E3F6e7e2034F8f96140", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x60eC904955CA843285B24E3F6e7e2034F8f96140" },
  "Guardian": { state: "verified", checkedAt: "2026-08-29T12:21:55Z", address: "0x75Bf4C326f054e655C7C138cD847154fEB3bAC19", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x75Bf4C326f054e655C7C138cD847154fEB3bAC19" },
  "Hull": { state: "verified", checkedAt: "2026-08-29T12:22:42Z", address: "0x9638da84aA4b30fB9350bb2cA33DCf0b81Ab3Bd2", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x9638da84aA4b30fB9350bb2cA33DCf0b81Ab3Bd2" },
  "MockRouter": { state: "verified", checkedAt: "2026-08-29T12:22:38Z", address: "0x68A1Ad5FB46c3Eb804F3375Cba702d806E1890B6", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x68A1Ad5FB46c3Eb804F3375Cba702d806E1890B6" },
  "MockWMON": { state: "verified", checkedAt: "2026-08-29T12:22:32Z", address: "0xEf6Cc6228A39cF8433754dcBe863275AC6Dc5DB5", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0xEf6Cc6228A39cF8433754dcBe863275AC6Dc5DB5" },
  "PauseGuardian": { state: "verified", checkedAt: "2026-10-02T14:19:25Z", address: "0x6B12C7375FC96dc2f805Cd1e28999b711d1C3e17", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x6B12C7375FC96dc2f805Cd1e28999b711d1C3e17" },
  "PerplVenue": { state: "verified", checkedAt: "2026-08-29T12:22:26Z", address: "0x59fc4C09eF7Dc0b754B74d7AEe21EeAC1c94aD6C", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x59fc4C09eF7Dc0b754B74d7AEe21EeAC1c94aD6C" },
  "SimVenue": { state: "verified", checkedAt: "2026-08-29T12:22:21Z", address: "0xD8730205Ab716Bc2FcA2FfF653e1390DFC4Fe85d", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0xD8730205Ab716Bc2FcA2FfF653e1390DFC4Fe85d" },
  "SimulatedEngine": { state: "verified", checkedAt: "2026-10-02T14:20:11Z", address: "0x2174EBa2b5b20B6CA128FD2BCfc74A9c0736ffED", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x2174EBa2b5b20B6CA128FD2BCfc74A9c0736ffED" },
  "TimelockController": { state: "verified", checkedAt: "2026-10-02T14:19:21Z", address: "0xA75526e97f0b0f5d2f9B06f0eD0C7DB9545A9f80", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0xA75526e97f0b0f5d2f9B06f0eD0C7DB9545A9f80" },
  "TrancheController": { state: "verified", checkedAt: "2026-10-02T14:19:48Z", address: "0x717147E566C42D8926c258fCe24B1746ceDB1740", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x717147E566C42D8926c258fCe24B1746ceDB1740" },
  "Tranches": { state: "verified", checkedAt: "2026-08-29T12:22:12Z", address: "0x7Df78EA918FA4531a74b79CE0a53a6D94B72E373", url: "https://sourcify-api-monad.blockvision.org/v2/contract/10143/0x7Df78EA918FA4531a74b79CE0a53a6D94B72E373" },
};

/** Unknown is the safe default: a name with no entry is never shown as verified. */
export function verificationOf(name: string): VerificationEntry {
  return VERIFICATION[name] ?? { state: "unknown", checkedAt: null, address: "" };
}
