// GENERATED by scripts/sync-v2-app.mjs from deployments/testnet-v2.json — do not edit.
export const RELEASE = {
  schemaVersion: 1,
  environment: "testnet",
  chainId: 10143,
  deployedBlock: 67565062,
  venue: "sim",
  status: "SIMULATED engine; G01-G04 BLOCKED; not audited",
  timelockDelaySeconds: 300,
} as const;

export const V2 = {
  "AssetCustody": "0x800b830A3B6C63bcAABAa9128A217a03aaD7377d",
  "BallastToken": "0x278E531dBc080Fa4C0314da9c1592bA6f148926d",
  "ClaimEscrow": "0x6B60BcdF3a2DB8762Ade4b05D590aB0aCf0FDF3d",
  "DemoUSD": "0x959E54DcF8576856F7A9424190a9751c68739495",
  "PauseGuardian": "0x6B12C7375FC96dc2f805Cd1e28999b711d1C3e17",
  "SimulatedEngine": "0x2174EBa2b5b20B6CA128FD2BCfc74A9c0736ffED",
  "TimelockController": "0xA75526e97f0b0f5d2f9B06f0eD0C7DB9545A9f80",
  "TrancheController": "0x717147E566C42D8926c258fCe24B1746ceDB1740"
} as const;

export const ROLES = {
  "deployer": "0x64d81F3E47c9Ba737BE17f8F9E5398EBf7e9Ce86",
  "governanceSafe": "0x12B2A61ac4108C722A6Dd1530fb7142cE9BD2Ee5",
  "guardian": "0x12B2A61ac4108C722A6Dd1530fb7142cE9BD2Ee5",
  "operator": "0xd1588b68d6beac5328E61166b952619b63dbf16f"
} as const;
