#!/usr/bin/env node
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts/out");
const abiDir = join(root, "app/lib/abis");
mkdirSync(abiDir, { recursive: true });

const contracts = [
  ["DemoUSD.sol", "DemoUSD"],
  ["BlitzVault.sol", "BlitzVault"],
  ["Tranches.sol", "Tranches"],
  ["EngineLite.sol", "EngineLite"],
  ["SimVenue.sol", "SimVenue"],
  ["Guardian.sol", "Guardian"],
];

for (const [file, name] of contracts) {
  const src = join(out, file, `${name}.json`);
  if (!existsSync(src)) {
    console.error("missing", src);
    process.exit(1);
  }
  const json = JSON.parse(readFileSync(src, "utf8"));
  writeFileSync(join(abiDir, `${name}.json`), JSON.stringify(json.abi, null, 2));
  console.log("copied", name);
}

const addressesPath = join(root, "ADDRESSES.json");
if (!existsSync(addressesPath)) {
  console.error("missing ADDRESSES.json — deploy first");
  process.exit(1);
}
const addresses = JSON.parse(readFileSync(addressesPath, "utf8"));
const ts = `// Generated by pnpm sync — do not edit by hand.
export const CHAIN_ID = ${addresses.chainId} as const;
export const DEPLOYED_BLOCK = ${addresses.deployedBlock} as const;
export const VENUE_MODE = ${JSON.stringify(addresses.venue)} as const;

export const ADDRESSES = ${JSON.stringify(addresses.contracts, null, 2)} as const;

export const REFS = ${JSON.stringify(addresses.refs, null, 2)} as const;

export function assertChain(chainId: number) {
  if (chainId !== CHAIN_ID) {
    throw new Error(\`Wrong chain: expected \${CHAIN_ID}, got \${chainId}\`);
  }
}
`;
writeFileSync(join(root, "app/lib/addresses.ts"), ts);
console.log("wrote app/lib/addresses.ts");
