#!/usr/bin/env node
// Generate the app's v2 book bindings from the build and the release manifest:
//   contracts/out/<C>.sol/<C>.json      -> app/lib/book/abis/<C>.json
//   deployments/<env>-v2.json           -> app/lib/book/release.ts
// `--check` fails when the committed files differ (CI drift guard).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const env = process.env.V2_ENV ?? "testnet";
const check = process.argv.includes("--check");
const outDir = join(root, "app/lib/book/abis");

const CONTRACTS = ["TrancheController", "AssetCustody", "ClaimEscrow", "BallastToken", "PauseGuardian", "SimulatedEngine", "DemoUSD"];

const files = [];
for (const name of CONTRACTS) {
  const src = join(root, "contracts/out", `${name}.sol`, `${name}.json`);
  if (!existsSync(src)) {
    console.error(`missing ${src} — run forge build first`);
    process.exit(1);
  }
  const abi = JSON.parse(readFileSync(src, "utf8")).abi;
  files.push([join(outDir, `${name}.json`), JSON.stringify(abi, null, 2) + "\n"]);
}

const manifestPath = join(root, "deployments", `${env}-v2.json`);
if (!existsSync(manifestPath)) {
  console.error(`missing ${manifestPath} — deploy first`);
  process.exit(1);
}
const m = JSON.parse(readFileSync(manifestPath, "utf8"));
const release = `// GENERATED by scripts/sync-v2-app.mjs from deployments/${env}-v2.json — do not edit.
export const RELEASE = {
  schemaVersion: ${m.schemaVersion},
  environment: ${JSON.stringify(m.environment)},
  chainId: ${m.chainId},
  deployedBlock: ${m.deployedBlock},
  venue: ${JSON.stringify(m.venue)},
  status: ${JSON.stringify(m.status)},
  timelockDelaySeconds: ${m.timelockDelaySeconds},
} as const;

export const V2 = ${JSON.stringify(m.contracts, null, 2)} as const;

export const ROLES = ${JSON.stringify(m.roles, null, 2)} as const;
`;
files.push([join(root, "app/lib/book/release.ts"), release]);
// The SDK ships the same release manifest, so integrators get the reviewed addresses.
files.push([
  join(root, `packages/sdk/src/manifests/${env}.ts`),
  `// GENERATED by scripts/sync-v2-app.mjs from deployments/${env}-v2.json — do not edit.\nexport const ${env.toUpperCase()}_V2 = ${JSON.stringify(m, null, 2)} as const;\n`,
]);

mkdirSync(outDir, { recursive: true });
mkdirSync(join(root, "packages/sdk/src/manifests"), { recursive: true });
let drift = 0;
for (const [path, body] of files) {
  const rel = path.slice(root.length + 1);
  const have = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (have === body) {
    console.log(`ok       ${rel}`);
  } else if (check) {
    console.error(`DRIFT    ${rel} — run node scripts/sync-v2-app.mjs`);
    drift++;
  } else {
    writeFileSync(path, body);
    console.log(`wrote    ${rel}`);
  }
}
if (drift) process.exit(1);
